export const RECIPE_SET = 'RECIPE_SET'
export const RECIPE_TOGGLE_DETAIL = 'RECIPE_TOGGLE_DETAIL'
export const RECIPES_SET = 'RECIPES_SET'
export const RECIPES_BY_ID_SET = 'RECIPES_BY_ID_SET'
export const RECIPES_KEYWORDS_SET = 'RECIPES_KEYWORDS_SET'

export const SCROLL_REACHED_BOTTOM = 'SCROLL_REACHED_BOTTOM'
export const SCROLL_LAST_EVENT = 'SCROLL_LAST_EVENT'

export const ACTION_CREATE = 'ACTION_CREATE'
export const ACTION_DELETE = 'ACTION_DELETE'
export const ACTION_UPDATE = 'ACTION_UPDATE'

export const HOME_SET_CURRENT_ACTION = 'HOME_SET_CURRENT_ACTION'
